### ISSUE TITLE
Empty SDL2 window?

### ISSUE THREAD

**Issue by vanfanel** [cuckydev/SoniCpp#1]
Hi there,

I am trying some opensource engines on GNU/Linux (both Ubuntu and Raspberry Pi OS) so I was very happy to find this accurate Sonic 1 engine!
However, when I launch re resulting executable after building from latest GIT sources, all I get is an empty SDL2 window.
Should I provide engine data somehow?

Thanks!

**Comment by cuckydev** [comment]
Hey, I'm very sorry that I've only seen this now. This project isn't currently being worked on since I'm busy with other projects. The project is in a very early state (which to be honest, I should've put in the description or README), so yeah, it's pretty much just an empty SDL2 window with some unused code. Sorry about that.
